/**
 * ATTENTION - ONLY EDIT THIS FILE IF YOU KNOW WHAT YOU ARE DOING
 */

import "./globals.css";
import type { Metadata } from "next";

import { jetbrains_mono } from "@/utils/font-loader";

export const metadata: Metadata = {
  title: "yuHacks(2023) - Create, connect, code",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body className={jetbrains_mono.className}>{children}</body>
    </html>
  );
}
